[model]
General_conditions = "Default"
nx = 5  # Discretisation points in x
ny = 5  # Discretisation points in y
nstack = 9  # Simulated repeat units nstack = 2*(number of layers) - 1
nRC = 3  # Number of R-C pairs in simulation
Module = "No"
Module_4T = "No"
Electrical_type = "ECN_Plain"
ECN_method = "Neo"  # Model structure: "Neo"/"General"
Model = "EandT"  # Model type: "EandT"/"E"/"T" (Electrical and Thermal/Electrical only/Thermal only)
E-T_coupling = "two-way"  # Coupling way of electrical-thermal model: "two-way"/"NA"
Heat_gen = "Yes"  # Heat generation consideration: "Yes"/"No"
Entropy = "Yes"  # Entropic heat consideration: "Yes"/"No"
Ageing = "No"  # Ageing: "Yes"/"No"
BoL_ageing = "No"  # Beginning of life ageing model: "Yes"/"No"
CC = "Yes"  # Current collector resistance consideration: "Yes"/"No"
R0_minus_Rcc = "No"  # Subtract current collector resistance from R0: "Yes"/"No"
Thermal_tab = "Default"  # "Tabless_virtual/Default"; positive/negative tab between jellyroll and can; "Tabless_virtual": At positive tab, Al and Can are thermally connected. At negative tab, Cu and Can are thermally connected; "Default": at positive and negative tab, tab and can are thermally insulated
Electrical_tab = "Default"  # "Tabless_virtual/Default"
Thermal_partition_can = "Yes"  # Consideration of can: "Yes"/"No"

[runtime_options]
Count = "Yes"  # Calculate run time each section: "Yes"/"No"
Echeck = "No"  # Whole model energy conservation check:  "Yes"/"No"
Get_unnecessary_info = "No"  # Other info calculation, energy density, bulk properties etc.: "Yes"/"No"
Q_charact_separate = "No"  # Capacity characterisation: "Yes"/"No"
TemBC_vectorCN_check = "No"  # Check Dirichlet temperature BC for temperature-constrained BC: "Yes"/"No"
TemBC_smoothing = "No"  # Temperature BC smoothing: "Yes"/"No"
CheckBC_4T = "No"  # Check thermal model BC right or not: "Yes"/"No". This only applies when Tem BC is used, check Dirichlet Temperature BC. This only applies for Temperature constrained BC
Smoothing_stiffness = 1

[operating_conditions]
C_rate = 1  # Define simulation current
I_ext_fpath = ""  # Use time-varying current: "/path/to/file/containing/current/data" / ""
dt = 1  # Timestep (s)
SoC_initial = 1  # State of charge initial condition
Current_direction = 1  # 1/-1 for discharge/charge
IV_mode = 0  # Mode of operation: 0/1 for constant current/voltage
V_highlimit_single = 4.2  # Charge cut-off voltage
V_lowlimit_single = 2.7  # Discharge cut-off voltage
Tab_surface_scheme = "AllConv"  # Tab surface cooling scheme: AllConv/AllTem/TabConv_SurTem/TabTem_SurConv/SurfaceCooling/TabCooling/UserDefine     "TabCoolAgeing"/"TwoSurfaceCoolAgeing" Cooling schemes for cell stack surfaces applies only when Thermal_partition_can="No" i.e. No can, then apply BC directly on stack/jellyroll surface
Tab_thermal_path = "No"  # Internal tab thermal connection jellyroll/stack to can: "Yes"/"No"
Cap_heatgen = "No"  # Safety cap heatgen: "Yes"/"No"
T_cooling = 298.15  # Cooling temperature for the cell stack
T_initial = 298.15  # Initial temperature
T_fixed = 298.15  # Temperature when no electrical-thermal coupling
Rcc = 1.3270e-2  # Current collector resistance (used if R0_minus_Rcc = "Yes")
Rcap = 5e-2  # Cylindrical cell cap resistance
Can_scheme = "AllConv"  # Can cooling scheme: "AllConv"/"AllTem"/"TabConv_SurTem"/"TabTem_SurConv"/"SurfaceCooling"/"TabCooling"/"UserDefine"
AllConv_h = 30.0  # Cooling schemes for cell can surfaces: "AllConv"/"BaseCoolCond" etc. applies only when Thermal_partition_can = "Yes" i.e. when can is there then apply BC directly on can surface
Thermal_BC_core = "SepAir"  # Thermal model core BC: "SepFill"/"SepAir"
n_air = 0.5  # ratio of b0 to b0air; only applies when Thermal_BC_core = "SepAir"
CanSepFill_membrane = "No"  # between the can and jellyroll space i.e. no filling of seperator in the blank space. only applies when Thermal_patition_can="Yes"

[cell]
Form_factor = "Cylindrical"  # Cell form factor "Pouch"/"Cylindrical"/"Prismatic"
Eparam = "Cylindrical_Cell1"  # Cell name
Cells_name = ["cell_1"]

[cell.geometry]
nstack_real = 22  # Number of repeat units in real cell
delta_an_real = 8.615e-5  # thickness; an: anode
delta_ca_real = 7.703e-5  # ca: cathode
delta_sep_real = 1.4e-5  # sep: separator
delta_core_real = 1.92e-3  # core radius
delta_Al_real = 1.633e-5  # Al: aluminium
delta_Cu_real = 2.7e-5  # Cu: copper
delta_el_real = 1.7718e-4  # el: electrode pair
Lx_electrodes_real = 5.212683e-2  # electrode x dimension
Ly_electrodes_real = 5.212683e-2  # electrode y dimension
Lx_cell = 5.212683e-2 # cell x dimension
Ly_cell = 5.212683e-2 # cell y dimension
Casing_delta_polyamide = 2.5e-5
Casing_delta_polypropylene = 4e-5
Casing_delta_Al = 4e-5

[cell.electrical]
Capacity_rated0 = 1.8e4  # Cell capacity, Ah
Nominal_voltage = 3.63
Energy = 6.6534e4
Conductivity_Al = 3.5e7  # conductivity, S/m^3
Conductivity_Cu = 6e7

[cell.physical]
Density_an = 1.555e3  # density, kg/m^3
Density_ca = 2.895e3
Density_sep = 1.017e3
Density_Al = 2.702e3
Density_Cu = 8.933e3
Casing_density_polyamide = 1.15e3  # only relevant if casing is on
Casing_density_polypropylene = 9.2e2
Casing_density_Al = 2.702e3

[cell.thermal]
Specific_heat_capacity_an = 1.437e3  # specific heat capacity, J/kg/K
Specific_heat_capacity_ca = 1.27e3
Specific_heat_capacity_sep = 1.978e3
Specific_heat_capacity_Al = 9.03e2
Specific_heat_capacity_Cu = 3.85e2
Conductivity_an = 1.58  # thermal conductivity, W/m/K
Conductivity_ca = 1.04
Conductivity_sep = 3.4e-1
Conductivity_Al = 2.38e2
Conductivity_Cu = 3.98e2

[cell.LUTs]
interp = "Interp"  # LUT interpolation or fitting function: "Fitting"/"Interp"
interp_order = "linear"  # LUT interpolation type: "Linear"/"Cubic"

[can.geometry]
delta_real = 1.6e-4
delta_surface = 1.05e-4
delta_base = 1.05e-4

[can.physical]
Density = 8.05e3

[can.thermal]
Specific_heat_capacity_real = 4.2e2
Specific_heat_capacity_surface = 4.2e2
Specific_heat_capacity_base = 4.2e2
Conductivity = 4.5e1
Conductivity_sep_base = 2.6

[tab.geometry]
A = 5.775e-7
L = 1.1e-2

[tab.physical]
Density = 2.702e3

[tab.thermal]
Conductivity = 2.38e2
Specific_heat_capacity = 9.03e2

[membrane.geometry]
delta = 7e-5

[membrane.thermal]
Conductivity = 3.4e-1

[form-factor-specific]
LG_can = 7e-2
LG_jellyroll = 6.5e-2

[module]
General_conditions_module = "Default"
Modules_name = ["module_1"]
Modules_4T_name = ["module_1_4T"]
Current_direction_module = 1
IV_mode_module = 0
V_ext_module = 4.2
SoC_initial_module = 1
C_rate_module = 1
BC_module = "Ribbon_cooling"
BC_module_4T = "Ribbon_cooling"
BC_ribbon = "Single_Tab_Cooling"  # "Single_Tab_Cooling/AllConv"
Cells_num_module = 2
Parts_num_module = 3  # number of thermal parts in Module
LUT_Scale_Factor_Rs = 2  # Factor by which R's in LUT is to be changed in case of multi-jellyroll scenario
LUT_Scale_Factor_Cs = 0.5  # Factor by which C's in LUT is to be changed in case of multi-jellyroll scenario

[solver]
Linsolver_E = "Sparse"  # Solver for electrical model: "Sparse"/"General"
Linsolver_T = "Sparse"  # Solver for thermal model: "Sparse"/"General"
Thermal_solver = "CN"  # Thermal solver type (implicit/explicit): "CN"/"Explicit"
Linsolver_E_module = "Sparse"

[postprocessing]
PostProcessor = "Yes"  # Run post-processor at cell level: "Yes"/"No"
PostProcess_cell_id = "cell_1"  # Postprocess cell_1 by default
PostProcessor_module = "Yes"  # Run post-processor at module level: "Yes"/"No"
PostProcess_module_id = "module_1"  # Postprocess module_1 by default
Visualisation_method = "mayavi"  # Visualisation method type: "mayavi"/"plotly"
Temp_levels = 40  # Number of divisions on colour bar
Temp_min = 15.0  # Minimum temperature on colour bar
Temp_max = 35.0  # Maximum temperature on colour bar
PlotLUT = "No"  # Plotting LUTs: "Yes"/"No"
PlotNode = "No"  # Plot nodes in figure: "Yes"/"No"
Fig1to9 = "Yes"  # Plot figures 1 to 9:  "Yes"/"No"
PopFig_or_SaveGIF_instant = "No"
PopFig_or_SaveGIF_replay = "GIF"
Plot_type_preprocess = "instant"
Plot_type_postprocess = "reply"
GIFdownsample_num = 1

[postprocessing.mayavi]
Show_cell_num = "No"  # Show cell number in mayavi plot: "Yes"/"No"
Cells_Xinterval_module = 0.05  # spatial locations in a module for cells
Cells_Yinterval_module = 0.0
Cells_Zinterval_module = 0.0

[ribbon]
T_cooling = 298.15  #cooling temperature only for ribbon
h = 3.0  # convective heat transfer coefficient for ribbon surfaces not T constrained

[ribbon.geometry]
S_cooling_size_x = 2e-2  # input x dimension (angular direction) of rectangle cooling region
S_cooling_size_y = 5.5e-2  # input y dimension (height direction) of rectangle cooling region
S_cooling_h = 10.0  # input convection coefficient for area except cooling region
S_cooling_cell_spacing = 3e-2  # input cell spacing: spacing of cell-ribbon center contacting points (ind0_Geo_Can_S_cooling_node38_4T)
S_cooling_ribbon_addlength = 5e-2  # input ribbon added length to ribbon right surface
Lz = 5e-3
nz = 2

[ribbon.physical]
Density = 2.702e3

[ribbon.thermal]
Conductivity = 2.38e2
Specific_heat_capacity = 9.03e2
